### PR TITLE
Add the option for a web-server

### PR DESCRIPTION
**Pull request by allancoding**
To fix the problem with: [https://github.com/ethanaobrien/emuserver/issues/7](https://github.com/ethanaobrien/emuserver/issues/7)
This can now be a web-server!

### CODE REVIEW

**Comment by ethanaobrien** [comment]
What's the `passwordforserver` option do?

**Comment by allancoding** [comment]
It is the password for the page to start or stop the server.

**Comment by ethanaobrien** [comment]
Oh ok this is really cool! I'll be able to check a few things tomorrow then I'll merge

**Comment by allancoding** [comment]
This is an example you can see: [https://emuserver.herokuapp.com/](https://emuserver.herokuapp.com/)
The username is: `admin`
The password is: `mypassword`

**Comment by allancoding** [comment]
Well I made it a web server so that explains most of it. I added you to the project.

**Comment by ethanaobrien** [comment]
Thank you!

**Comment by ethanaobrien** [comment]
I'm merging. Looks good!

**Comment by ethanaobrien** [comment]
oops. Well it merged

**Comment by allancoding** [comment]
I see what the problem is with the deploying on heroku failure is.
Make a new branch called `web-server` and I will push the working code to it. The branch can't be blank so put a blank file in it.Then you can deploy on heroku the `web-server` branch. If you look at my fork you can see what I mean

**Comment by ethanaobrien** [comment]
Yeah it would be pretty cool I would like to do that. (it could be the emulatorjs demo/default server) What are the limits of heroku and netlify. Does netlify support running these kinds of apps?

**Comment by allancoding** [comment]
Yes that is what I thought. Sadly no netlify only supports node.js builds not servers but you can use dns for these problems. Here join this discode server I just made it we can use it to communicate better with the chat. I am a self learner at 14.
[https://discord.gg/znXbuFFc](https://discord.gg/znXbuFFc) this link will expire after one click.

**Comment by ethanaobrien** [comment]
Ok cool, I wont be able to click it for a while because Im at school. I am self taught and 17

**Comment by allancoding** [comment]
Ha I am too. Do you have a verified heroku account?

**Comment by ethanaobrien** [comment]
no I do not. Sorry

**Comment by allancoding** [comment]
Would it be better if we did this in a email?

**Pull request merged**
